name = "TZJFileData"
uuid = "dc5dba14-91b3-4cab-a142-028a31da12f7"
authors = ["Curtis Vogt <curtis.vogt@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
