---
name: Build
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tzdata_version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JULIA_PROJECT: gen
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: julia-actions/cache@v1
      - name: Instantiate
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Build tzdata
        id: build
        shell: julia --color=yes {0}
        run: |
          include(joinpath(pwd(), "gen", "make.jl"))
          (; tarball_path, tarball_sha256, new_version, commit_message) = update_tzdata()
          @show tarball_path
          open(ENV["GITHUB_OUTPUT"], "a") do io
              println(io, "key=$(basename(tarball_path))-$(tarball_sha256)")
              println(io, "tarball_path=$tarball_path")
              println(io, "commit_message=$commit_message")
              println(io, "branch=gh/v$(new_version)")
          end
          println("commit_message=$commit_message")
          println("branch=gh/v$(new_version)")
      - name: Debug
        run: |
          echo "${{ steps.build.outputs.tarball_path }}"
          git diff
      - uses: actions/upload-artifact@v4
        id: action-artifact
        with:
          name: ${{ steps.build.outputs.key }}
          path: ${{ steps.build.outputs.tarball_path }}
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     add-paths: |
      #       Project.toml
      #       Artifacts.toml
      #     commit-message: ${{ steps.build.outputs.commit_message }}
      #     branch: ${{ steps.build.outputs.branch }}
