name: Test2
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v3
        id: action-artifact
        with:
          workflow: Test.yaml
          branch: cv/workflow-test
          name: test
      - run: |
          ls -la
